/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package benz.Mis;
import benz.Welcome;
import javax.swing.*;
/**
 *
 * @author Admin
 */
public class XnO extends javax.swing.JFrame {

    /**
     * Creates new form XnO
     */
    public XnO() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(5, 10, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(244, 153, 0));
        jButton1.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton1.setForeground(new java.awt.Color(57, 194, 255));
        jButton1.setText("x");
        jButton1.setBorder(null);
        jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(244, 153, 0));
        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 148, 210));
        jLabel1.setText(" \n");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 153, 0), 1, true));

        jButton10.setBackground(new java.awt.Color(244, 153, 0));
        jButton10.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton10.setForeground(new java.awt.Color(57, 194, 255));
        jButton10.setText("o");
        jButton10.setBorder(null);
        jButton10.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(244, 153, 0));
        jButton2.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton2.setForeground(new java.awt.Color(57, 194, 255));
        jButton2.setText("x");
        jButton2.setBorder(null);
        jButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(244, 153, 0));
        jButton11.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton11.setForeground(new java.awt.Color(57, 194, 255));
        jButton11.setText("o");
        jButton11.setBorder(null);
        jButton11.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(244, 153, 0));
        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(32, 148, 210));
        jLabel2.setText("  ");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 153, 0), 1, true));

        jButton3.setBackground(new java.awt.Color(244, 153, 0));
        jButton3.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton3.setForeground(new java.awt.Color(57, 194, 255));
        jButton3.setText("x");
        jButton3.setBorder(null);
        jButton3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(244, 153, 0));
        jButton12.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton12.setForeground(new java.awt.Color(57, 194, 255));
        jButton12.setText("o");
        jButton12.setBorder(null);
        jButton12.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(244, 153, 0));
        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 70)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(32, 148, 210));
        jLabel3.setText(" \n");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 153, 0), 1, true));

        jButton4.setBackground(new java.awt.Color(244, 153, 0));
        jButton4.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton4.setForeground(new java.awt.Color(57, 194, 255));
        jButton4.setText("x");
        jButton4.setBorder(null);
        jButton4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(244, 153, 0));
        jButton13.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton13.setForeground(new java.awt.Color(57, 194, 255));
        jButton13.setText("o");
        jButton13.setBorder(null);
        jButton13.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(244, 153, 0));
        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(32, 148, 210));
        jLabel4.setText(" \n");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 153, 0), 1, true));

        jButton5.setBackground(new java.awt.Color(244, 153, 0));
        jButton5.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton5.setForeground(new java.awt.Color(57, 194, 255));
        jButton5.setText("x");
        jButton5.setBorder(null);
        jButton5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(244, 153, 0));
        jButton14.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton14.setForeground(new java.awt.Color(57, 194, 255));
        jButton14.setText("o");
        jButton14.setBorder(null);
        jButton14.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(244, 153, 0));
        jLabel5.setFont(new java.awt.Font("Californian FB", 1, 70)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(32, 148, 210));
        jLabel5.setText(" \n");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 153, 0), 1, true));

        jButton6.setBackground(new java.awt.Color(244, 153, 0));
        jButton6.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton6.setForeground(new java.awt.Color(57, 194, 255));
        jButton6.setText("x");
        jButton6.setBorder(null);
        jButton6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(244, 153, 0));
        jButton15.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton15.setForeground(new java.awt.Color(57, 194, 255));
        jButton15.setText("o");
        jButton15.setBorder(null);
        jButton15.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(244, 153, 0));
        jLabel6.setFont(new java.awt.Font("Californian FB", 1, 70)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(32, 148, 210));
        jLabel6.setText(" \n");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 153, 0), 1, true));

        jButton7.setBackground(new java.awt.Color(244, 153, 0));
        jButton7.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton7.setForeground(new java.awt.Color(57, 194, 255));
        jButton7.setText("x");
        jButton7.setBorder(null);
        jButton7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(244, 153, 0));
        jButton16.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton16.setForeground(new java.awt.Color(57, 194, 255));
        jButton16.setText("o");
        jButton16.setBorder(null);
        jButton16.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(244, 153, 0));
        jLabel7.setFont(new java.awt.Font("Californian FB", 1, 70)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(32, 148, 210));
        jLabel7.setText(" \n");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 153, 0), 1, true));

        jButton8.setBackground(new java.awt.Color(244, 153, 0));
        jButton8.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton8.setForeground(new java.awt.Color(57, 194, 255));
        jButton8.setText("x");
        jButton8.setBorder(null);
        jButton8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(244, 153, 0));
        jButton17.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton17.setForeground(new java.awt.Color(57, 194, 255));
        jButton17.setText("o");
        jButton17.setBorder(null);
        jButton17.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(244, 153, 0));
        jLabel8.setFont(new java.awt.Font("Californian FB", 1, 70)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(32, 148, 210));
        jLabel8.setText(" \n");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 153, 0), 1, true));

        jButton9.setBackground(new java.awt.Color(244, 153, 0));
        jButton9.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton9.setForeground(new java.awt.Color(57, 194, 255));
        jButton9.setText("x");
        jButton9.setBorder(null);
        jButton9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(244, 153, 0));
        jButton18.setFont(new java.awt.Font("Californian FB", 1, 55)); // NOI18N
        jButton18.setForeground(new java.awt.Color(57, 194, 255));
        jButton18.setText("o");
        jButton18.setBorder(null);
        jButton18.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(244, 153, 0));
        jLabel9.setFont(new java.awt.Font("Californian FB", 1, 70)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(32, 148, 210));
        jLabel9.setText(" \n");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 153, 0), 1, true));

        jLabel10.setFont(new java.awt.Font("Pristina", 1, 55)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TIC-TAC-TOE");

        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));

        jButton20.setBackground(new java.awt.Color(244, 153, 0));
        jButton20.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jButton20.setForeground(new java.awt.Color(57, 194, 255));
        jButton20.setText("Re-Play");
        jButton20.setBorder(null);
        jButton20.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(244, 153, 0));
        jButton21.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jButton21.setForeground(new java.awt.Color(57, 194, 255));
        jButton21.setText("Exit");
        jButton21.setBorder(null);
        jButton21.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(244, 153, 0));
        jButton22.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jButton22.setForeground(new java.awt.Color(57, 194, 255));
        jButton22.setText("Back");
        jButton22.setBorder(null);
        jButton22.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        jLabel1.setText(" X");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

        jLabel1.setText(" O");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        jLabel2.setText(" X");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        jLabel2.setText(" O");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        jLabel3.setText(" X");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:

        jLabel3.setText(" O");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        jLabel4.setText(" X");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:

        jLabel4.setText(" O");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        jLabel5.setText(" X");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:

        jLabel5.setText(" O");
        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        jLabel6.setText(" X");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:

        jLabel6.setText(" O");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        jLabel7.setText(" X");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:

        jLabel7.setText(" O");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        jLabel8.setText(" X");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:

        jLabel8.setText(" O");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        jLabel9.setText(" X");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:

        jLabel9.setText(" O");

        if(

            ((jLabel1.getText().equals(" X")) &&
                (jLabel2.getText().equals(" X"))  &&
                (jLabel1.getText().equals(" X"))) ||

            (jLabel4.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) ||

            (jLabel7.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel4.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X")) ||

            (jLabel2.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel8.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel6.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel1.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel9.getText().equals(" X")) ||

            (jLabel3.getText().equals(" X")) &&
            (jLabel5.getText().equals(" X")) &&
            (jLabel7.getText().equals(" X"))

        )

        {
            jLabel11.setText("Player X wins.!!");
        }

        else if(

            ((jLabel1.getText().equals(" O")) &&
                (jLabel2.getText().equals(" O"))  &&
                (jLabel1.getText().equals(" O"))) ||

            (jLabel4.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) ||

            (jLabel7.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel4.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O")) ||

            (jLabel2.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel8.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel6.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel1.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel9.getText().equals(" O")) ||

            (jLabel3.getText().equals(" O")) &&
            (jLabel5.getText().equals(" O")) &&
            (jLabel7.getText().equals(" O"))

        )

        {
            jLabel11.setText("Player O wins.!!");
        }

        else
        {

            if
            (

                !jLabel1.getText().isEmpty() &&
                !jLabel2.getText().isEmpty() &&
                !jLabel3.getText().isEmpty() &&
                !jLabel4.getText().isEmpty() &&
                !jLabel5.getText().isEmpty() &&
                !jLabel6.getText().isEmpty() &&
                !jLabel7.getText().isEmpty() &&
                !jLabel8.getText().isEmpty() &&
                !jLabel9.getText().isEmpty()

            )

            {
                jLabel11.setText("Its a DRAW.");
            }
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:

        jLabel1.setText("");
        jLabel2.setText("");
        jLabel3.setText("");
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel8.setText("");
        jLabel9.setText("");
        jLabel11.setText("");

        JOptionPane.showMessageDialog(rootPane, "Welcome.!!");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        new Welcome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XnO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XnO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XnO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XnO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XnO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
